### ISSUE TITLE
Consider including a time stamp in the generated header comments

### ISSUE THREAD

**Issue by bradrf** [monadicstack/frodo#51]
Yes, one can also rely on the file system (or finder), but that's an extra hop out of your editing env to evaluate "how recently was this created"? And I'm lazy!

**Comment by robsignorelli** [comment]
Seems like a no-brainer... and I apparently had no brain when I didn't do this initially.

**Comment by robsignorelli** [comment]
I updated the header for all of the files so that they still have the proper Go Generate first line (Generated by .... DO NOT EDIT.) but I split out the data fields onto separate lines so that it's easier to see those details at a glance. Here's an example:

```
// Code generated by Frodo - DO NOT EDIT.
//
//   Timestamp: Fri, 24 Sep 2021 07:20:25 EDT
//   Source:    relays/service.go
//   Generator: https://github.com/monadicstack/frodo
//
```
